import { db, projectsTable } from "@workspace/db";

const projects = [
  // Nairobi Region
  {
    title: "Karura Forest Community Borehole",
    slug: "karura-forest-community-borehole",
    county: "Nairobi",
    town: "Karura",
    region: "Nairobi Metropolitan",
    clientType: "Community",
    serviceType: "Borehole Drilling",
    depth: 120,
    yield: "3.5 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Drilled a 120m borehole serving 250 households in the Karura community, providing reliable clean water access.",
    challenge: "Hard granite rock formation requiring specialised diamond-tipped drill bits.",
    solution: "Used rotary percussion drilling with polymer mud stabilisation through the fractured granite zone.",
    outcome: "250 households now have 24-hour clean water access, reducing water collection time from 3 hours to zero.",
    featured: true,
    latitude: "-1.2500",
    longitude: "36.8350",
  },
  {
    title: "Ruiru Industrial Estate Water Supply",
    slug: "ruiru-industrial-estate",
    county: "Kiambu",
    town: "Ruiru",
    region: "Nairobi Metropolitan",
    clientType: "Commercial",
    serviceType: "Borehole Drilling",
    depth: 180,
    yield: "8.0 m³/hr",
    duration: "7 days",
    completionYear: 2024,
    description: "High-yield industrial borehole for a manufacturing complex in Ruiru, replacing expensive municipal water supply.",
    challenge: "Needed minimum 6 m³/hr yield for industrial cooling systems while navigating complex underground geology.",
    solution: "Conducted detailed hydrogeological survey before drilling, identifying the optimal aquifer at 145m depth.",
    outcome: "Industrial complex saves KES 2.1M annually on water costs. Full ROI achieved within 18 months.",
    featured: true,
    latitude: "-1.1466",
    longitude: "36.9620",
  },
  {
    title: "Ngong Hills Flower Farm Irrigation",
    slug: "ngong-hills-flower-farm",
    county: "Kajiado",
    town: "Ngong",
    region: "Rift Valley",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 95,
    yield: "5.2 m³/hr",
    duration: "4 days",
    completionYear: 2023,
    description: "Drilled borehole and installed solar pump system for 50-acre flower export farm on the Ngong Hills.",
    challenge: "Remote location with no grid power. Farm needed consistent irrigation for export-grade flower production.",
    solution: "Installed 7.5kW solar pump system with 20,000L elevated storage tank for gravity irrigation.",
    outcome: "Farm increased flower yield by 35%. Eliminated generator fuel costs of KES 180,000/month.",
    featured: true,
    latitude: "-1.3580",
    longitude: "36.6580",
  },

  // Coast Region
  {
    title: "Diani Beach Resort Desalination & Borehole",
    slug: "diani-beach-resort-borehole",
    county: "Kwale",
    town: "Diani Beach",
    region: "Coast",
    clientType: "Hospitality",
    serviceType: "Borehole Drilling",
    depth: 200,
    yield: "4.5 m³/hr",
    duration: "10 days",
    completionYear: 2022,
    description: "Drilled a 200m coastal borehole and installed reverse osmosis water treatment for a 5-star resort at Diani Beach.",
    challenge: "Coastal aquifer with high salinity (TDS 2,800 mg/L). Resort required potable water for 300+ guests daily.",
    solution: "Combined borehole with 5,000 LPH RO system and UV sterilisation. Brine management system for zero environmental impact.",
    outcome: "Resort now fully water-independent. Water quality exceeds WHO potable water standards.",
    featured: true,
    latitude: "-4.3200",
    longitude: "39.5700",
  },
  {
    title: "Kilifi County Government Water Project",
    slug: "kilifi-county-water-project",
    county: "Kilifi",
    town: "Kilifi Town",
    region: "Coast",
    clientType: "Government",
    serviceType: "Borehole Drilling",
    depth: 160,
    yield: "6.8 m³/hr",
    duration: "14 days",
    completionYear: 2023,
    description: "Multi-borehole water supply project for Kilifi town serving 4 public schools and 2 health centres.",
    challenge: "Needed to drill 3 boreholes in different geological zones and integrate them into one distribution network.",
    solution: "Conducted unified hydrogeological survey, drilled 3 boreholes and installed a centralised solar-powered pumping station.",
    outcome: "6 public institutions now have reliable water. 3,200 students and patients served daily.",
    featured: false,
    latitude: "-3.6330",
    longitude: "39.8500",
  },
  {
    title: "Malindi Fishermen's Cooperative Borehole",
    slug: "malindi-fishermen-cooperative",
    county: "Kilifi",
    town: "Malindi",
    region: "Coast",
    clientType: "Community",
    serviceType: "Borehole Drilling",
    depth: 80,
    yield: "2.8 m³/hr",
    duration: "4 days",
    completionYear: 2024,
    description: "Shallow borehole for the Malindi Fishermen's Cooperative, providing fresh water for fish processing and domestic use.",
    challenge: "Budget constraints required finding a productive shallow aquifer in a coastal sandy terrain.",
    solution: "Used electrical resistivity tomography to identify a productive sand aquifer at 65m depth.",
    outcome: "Cooperative saves KES 45,000/month on water tanker costs. Fish processing hygiene improved significantly.",
    featured: false,
    latitude: "-3.2170",
    longitude: "40.1290",
  },
  {
    title: "Mombasa Airport Road Hotel Complex",
    slug: "mombasa-airport-road-hotel",
    county: "Mombasa",
    town: "Changamwe",
    region: "Coast",
    clientType: "Hospitality",
    serviceType: "Pump Installation",
    depth: 145,
    yield: "5.0 m³/hr",
    duration: "3 days",
    completionYear: 2024,
    description: "Pump installation and borehole rehabilitation for a 120-room hotel near Mombasa's Moi International Airport.",
    challenge: "Existing borehole was underperforming due to incorrect pump sizing and worn screen.",
    solution: "Replaced pump with correctly sized 5.5kW Grundfos SP series, installed new stainless steel screen and rising main.",
    outcome: "Yield improved from 1.2 to 5.0 m³/hr. Hotel's water independence restored at 30% of new-drill cost.",
    featured: false,
    latitude: "-4.0480",
    longitude: "39.5930",
  },

  // Rift Valley Region
  {
    title: "Nakuru Dairy Farm Mega Borehole",
    slug: "nakuru-dairy-farm-mega-borehole",
    county: "Nakuru",
    town: "Nakuru",
    region: "Rift Valley",
    clientType: "Agricultural",
    serviceType: "Borehole Drilling",
    depth: 110,
    yield: "12.0 m³/hr",
    duration: "6 days",
    completionYear: 2023,
    description: "High-yield borehole for a 500-head dairy farm in Nakuru, supporting milking operations and cattle drinking water.",
    challenge: "Farm required minimum 10 m³/hr continuous supply for dairy operations and herd drinking.",
    solution: "Geophysical survey identified a deep volcanic aquifer. Drilled and developed the borehole achieving 12 m³/hr.",
    outcome: "Dairy farm increased milk production by 18% due to improved cattle hydration. Fully water-independent.",
    featured: true,
    latitude: "-0.3031",
    longitude: "36.0800",
  },
  {
    title: "Eldoret Teaching Hospital Borehole",
    slug: "eldoret-teaching-hospital",
    county: "Uasin Gishu",
    town: "Eldoret",
    region: "Rift Valley",
    clientType: "Healthcare",
    serviceType: "Borehole Drilling",
    depth: 195,
    yield: "7.5 m³/hr",
    duration: "9 days",
    completionYear: 2022,
    description: "Critical water supply borehole for a 350-bed teaching hospital in Eldoret, replacing unreliable municipal supply.",
    challenge: "Hospital required uninterrupted, pathogen-free water. Municipal supply had been failing 8-10 hours daily.",
    solution: "Drilled 195m borehole with full casing, installed submersible pump with automated pressure system and UV treatment.",
    outcome: "Hospital has had zero water-related interruptions since installation. Surgical theatre operations fully secured.",
    featured: true,
    latitude: "0.5200",
    longitude: "35.2700",
  },
  {
    title: "Bomet Tea Estate Irrigation Network",
    slug: "bomet-tea-estate-irrigation",
    county: "Bomet",
    town: "Bomet",
    region: "Rift Valley",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 88,
    yield: "4.0 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Solar-powered borehole and drip irrigation network for 120-acre tea estate in Bomet County.",
    challenge: "Tea requires precise water scheduling. Estate had been relying on seasonal rains causing yield inconsistency.",
    solution: "Installed 5kW solar pump with automated irrigation controller delivering 35L/min to 120 acres via drip lines.",
    outcome: "Tea yield increased 25%. Estate now qualifies for premium export pricing due to consistent leaf quality.",
    featured: false,
    latitude: "-0.7800",
    longitude: "35.3400",
  },
  {
    title: "Naivasha Horticulture Farm Water System",
    slug: "naivasha-horticulture-farm",
    county: "Nakuru",
    town: "Naivasha",
    region: "Rift Valley",
    clientType: "Agricultural",
    serviceType: "Borehole Drilling",
    depth: 72,
    yield: "9.5 m³/hr",
    duration: "3 days",
    completionYear: 2024,
    description: "Shallow borehole tapping the productive Lake Naivasha aquifer for a 200-acre horticulture export farm.",
    challenge: "Farm needed high-yield shallow borehole close to Lake Naivasha without disturbing the riparian zone.",
    solution: "Sited borehole 800m from the lake edge, drilled to 72m tapping the productive Naivasha aquifer system.",
    outcome: "Farm exports 8 tonnes of French beans weekly to Europe. 120 employees fully employed year-round.",
    featured: false,
    latitude: "-0.7200",
    longitude: "36.4320",
  },
  {
    title: "Kericho County School Cluster",
    slug: "kericho-school-cluster",
    county: "Kericho",
    town: "Kericho",
    region: "Rift Valley",
    clientType: "Education",
    serviceType: "Borehole Drilling",
    depth: 105,
    yield: "3.2 m³/hr",
    duration: "5 days",
    completionYear: 2022,
    description: "Borehole and water distribution system serving 5 secondary schools in Kericho County.",
    challenge: "5 schools within 3km radius each had independent broken boreholes. Needed consolidated solution.",
    solution: "Drilled one new strategic high-yield borehole and connected all 5 schools via HDPE pipeline network.",
    outcome: "4,800 students now have reliable clean water. School KCSE scores improved as girls reduced water-fetching time.",
    featured: false,
    latitude: "-0.3690",
    longitude: "35.2860",
  },

  // Western Kenya
  {
    title: "Kisumu Port Industrial Zone",
    slug: "kisumu-port-industrial-zone",
    county: "Kisumu",
    town: "Kisumu",
    region: "Nyanza",
    clientType: "Commercial",
    serviceType: "Borehole Drilling",
    depth: 130,
    yield: "6.2 m³/hr",
    duration: "6 days",
    completionYear: 2023,
    description: "Industrial borehole for fish processing factory at Kisumu Port, replacing expensive water bowser deliveries.",
    challenge: "Lake Victoria shoreline geology with unstable lacustrine sediments requiring careful casing design.",
    solution: "Used telescoping casing technique with gravel pack to stabilise the sandy aquifer at 95m depth.",
    outcome: "Factory processes 15 tonnes of Nile perch daily. Water bowser costs of KES 320,000/month eliminated.",
    featured: true,
    latitude: "-0.1022",
    longitude: "34.7617",
  },
  {
    title: "Kakamega Sugar Cane Cooperative",
    slug: "kakamega-sugarcane-cooperative",
    county: "Kakamega",
    town: "Mumias",
    region: "Western",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 85,
    yield: "3.8 m³/hr",
    duration: "4 days",
    completionYear: 2023,
    description: "Solar borehole pump system for 800-member sugarcane cooperative in Mumias, Western Kenya.",
    challenge: "Cooperative needed affordable irrigation for 1,200 acres of sugarcane with zero grid reliability in the area.",
    solution: "Drilled 2 boreholes 600m apart, installed 4kW solar pumps each feeding a shared irrigation reservoir.",
    outcome: "Cooperative increased sugarcane output by 30%. Members' average annual income rose by KES 45,000.",
    featured: false,
    latitude: "0.3367",
    longitude: "34.4892",
  },
  {
    title: "Bungoma Town Shopping Mall",
    slug: "bungoma-town-shopping-mall",
    county: "Bungoma",
    town: "Bungoma",
    region: "Western",
    clientType: "Commercial",
    serviceType: "Pump Installation",
    depth: 115,
    yield: "4.8 m³/hr",
    duration: "3 days",
    completionYear: 2024,
    description: "Pump installation and water system for a new 3-storey shopping mall in Bungoma town.",
    challenge: "Mall required constant pressure system feeding rooftop tanks, fire suppression, and sanitation simultaneously.",
    solution: "Installed variable-speed Grundfos pump with pressure vessel and automated control panel.",
    outcome: "Mall serves 800+ daily shoppers with zero water supply interruptions. Fully operational since installation.",
    featured: false,
    latitude: "0.5635",
    longitude: "34.5577",
  },
  {
    title: "Siaya County Water Authority Project",
    slug: "siaya-county-water-authority",
    county: "Siaya",
    town: "Siaya",
    region: "Nyanza",
    clientType: "Government",
    serviceType: "Borehole Drilling",
    depth: 145,
    yield: "5.5 m³/hr",
    duration: "8 days",
    completionYear: 2022,
    description: "Four-borehole water supply scheme for Siaya County Water Authority serving 12 villages in Gem Sub-County.",
    challenge: "Area had crystalline basement rocks with low groundwater potential. Previous drillers failed twice.",
    solution: "Comprehensive EM geophysical survey identified productive fracture zones. All 4 boreholes succeeded.",
    outcome: "12 villages (18,000 people) have reliable water. Village school attendance up 22% as girls free from water duties.",
    featured: true,
    latitude: "0.0607",
    longitude: "34.2881",
  },

  // Eastern Kenya
  {
    title: "Machakos Mango Farm Irrigation",
    slug: "machakos-mango-farm-irrigation",
    county: "Machakos",
    town: "Machakos",
    region: "Eastern",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 135,
    yield: "3.5 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Deep borehole and solar drip irrigation system for 80-acre mango and avocado export farm in Machakos.",
    challenge: "Machakos hard rock geology required deep drilling. Farm at high elevation made pipe pressure challenging.",
    solution: "Drilled through basement rock using air-foam drilling. Installed booster pump system for hilltop tanks.",
    outcome: "First mango harvest post-installation yielded 180 tonnes. Farm now exports to Middle East markets.",
    featured: false,
    latitude: "-1.5177",
    longitude: "37.2634",
  },
  {
    title: "Kitui Arid Lands Community Water",
    slug: "kitui-arid-lands-community-water",
    county: "Kitui",
    town: "Kitui",
    region: "Eastern",
    clientType: "Community",
    serviceType: "Borehole Drilling",
    depth: 220,
    yield: "2.2 m³/hr",
    duration: "12 days",
    completionYear: 2023,
    description: "Deep community borehole in semi-arid Kitui, funded by county government, serving 5 villages during drought.",
    challenge: "Extremely arid area. Water table at 180m with hard quartzite rock. Previous attempts abandoned at 150m.",
    solution: "Used air-hammer percussion drilling through quartzite. Borehole developed at 220m with modest but reliable yield.",
    outcome: "5 villages with 3,500 people no longer walk 15km for water. Borehole has maintained yield through 2 dry seasons.",
    featured: true,
    latitude: "-1.3670",
    longitude: "38.0105",
  },
  {
    title: "Meru County Referral Hospital",
    slug: "meru-county-referral-hospital",
    county: "Meru",
    town: "Meru",
    region: "Eastern",
    clientType: "Healthcare",
    serviceType: "Borehole Drilling",
    depth: 160,
    yield: "5.8 m³/hr",
    duration: "7 days",
    completionYear: 2022,
    description: "Emergency borehole for Meru Level 5 Referral Hospital after municipal supply failure during peak cholera season.",
    challenge: "Hospital was facing critical water crisis during cholera outbreak. Required fast-track drilling and commissioning.",
    solution: "Mobilised drilling rig within 24 hours. Drilled, cased, and commissioned the borehole in 7 working days.",
    outcome: "Hospital resumed full operations without water interruption. Borehole has been primary source for 2+ years.",
    featured: false,
    latitude: "0.0469",
    longitude: "37.6490",
  },
  {
    title: "Embu University College Water Supply",
    slug: "embu-university-college-water-supply",
    county: "Embu",
    town: "Embu",
    region: "Eastern",
    clientType: "Education",
    serviceType: "Borehole Drilling",
    depth: 140,
    yield: "4.5 m³/hr",
    duration: "6 days",
    completionYear: 2024,
    description: "Campus borehole for Embu University College serving 8,000 students, hostels, lecture halls and laboratories.",
    challenge: "University campus had 3 shallow boreholes all failing. Needed deep reliable source under the Mount Kenya aquifer.",
    solution: "Sited borehole on campus periphery tapping Mount Kenya volcanic aquifer. Installed 3-phase submersible pump.",
    outcome: "University eliminated water rationing entirely. KES 2.8M annual water bill reduced to KES 400K for electricity.",
    featured: false,
    latitude: "-0.5313",
    longitude: "37.4500",
  },

  // North Kenya
  {
    title: "Garissa Refugee Camp Emergency Water",
    slug: "garissa-refugee-camp-emergency-water",
    county: "Garissa",
    town: "Dadaab",
    region: "North Eastern",
    clientType: "Humanitarian",
    serviceType: "Borehole Drilling",
    depth: 90,
    yield: "3.0 m³/hr",
    duration: "5 days",
    completionYear: 2022,
    description: "Emergency water borehole for humanitarian organisation serving 25,000 displaced persons at Dadaab.",
    challenge: "Extremely remote location, 120km from nearest town. Sandy terrain with risk of borehole collapse.",
    solution: "Airlifted drilling equipment to site. Used heavy-duty PVC casing with cement seal against the surface sands.",
    outcome: "25,000 persons have UNHCR-standard water access (15L/person/day). Borehole running for 3+ years.",
    featured: true,
    latitude: "1.7600",
    longitude: "40.4300",
  },
  {
    title: "Turkana County Livestock Trough Network",
    slug: "turkana-livestock-trough-network",
    county: "Turkana",
    town: "Lodwar",
    region: "North Western",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 75,
    yield: "2.5 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Solar borehole and livestock watering network for pastoralist communities in Turkana County.",
    challenge: "Pastoralists losing livestock during droughts. Area had no electricity and extreme temperatures degrading equipment.",
    solution: "Installed heat-resistant solar pump with shaded panels. Built 5 livestock troughs connected by gravity pipeline.",
    outcome: "1,200 pastoralist households protected their livestock through 2023 drought. Zero livestock deaths from dehydration.",
    featured: false,
    latitude: "3.1190",
    longitude: "35.5973",
  },
  {
    title: "Isiolo Town Water Supply Augmentation",
    slug: "isiolo-town-water-supply",
    county: "Isiolo",
    town: "Isiolo",
    region: "North Eastern",
    clientType: "Government",
    serviceType: "Borehole Drilling",
    depth: 168,
    yield: "4.2 m³/hr",
    duration: "8 days",
    completionYear: 2023,
    description: "Isiolo county government borehole to supplement failing municipal supply during extended dry season.",
    challenge: "Alluvial aquifer had become depleted. Needed to find deeper crystalline basement aquifer.",
    solution: "Drilled past the shallow alluvial and into fractures in the crystalline basement at 145m depth.",
    outcome: "Isiolo town avoided severe water rationing during 2023 drought. 45,000 residents benefited.",
    featured: false,
    latitude: "0.3500",
    longitude: "37.5833",
  },

  // Central Kenya
  {
    title: "Nyeri County Coffee Cooperative",
    slug: "nyeri-coffee-cooperative-borehole",
    county: "Nyeri",
    town: "Nyeri",
    region: "Central",
    clientType: "Agricultural",
    serviceType: "Borehole Drilling",
    depth: 100,
    yield: "5.2 m³/hr",
    duration: "5 days",
    completionYear: 2024,
    description: "Borehole for Nyeri coffee cooperative wet mill, providing clean water for coffee cherry washing and processing.",
    challenge: "Coffee processing requires clean water. Existing stream supply was contaminated during heavy rains.",
    solution: "Drilled into the productive Mount Kenya aquifer. Installed multi-stage treatment for processing-grade water quality.",
    outcome: "Cooperative produces specialty-grade coffee with clean processing. Premium price improvement of 20% per kg.",
    featured: false,
    latitude: "-0.4167",
    longitude: "36.9500",
  },
  {
    title: "Kirinyaga Rice Irrigation Scheme",
    slug: "kirinyaga-rice-irrigation-scheme",
    county: "Kirinyaga",
    town: "Mwea",
    region: "Central",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 55,
    yield: "8.0 m³/hr",
    duration: "3 days",
    completionYear: 2023,
    description: "High-yield shallow borehole for Mwea Irrigation Scheme supplementing Thiba River during dry seasons.",
    challenge: "Mwea rice farmers faced water shortages in the long dry season when Thiba River flow dropped critically.",
    solution: "Drilled 2 boreholes tapping the shallow Tana Basin aquifer. Solar pumps deliver water to irrigation canals.",
    outcome: "Farmers completed two full rice cycles in 2023 instead of one. 1,500 farmer households benefited.",
    featured: false,
    latitude: "-0.6400",
    longitude: "37.3500",
  },
  {
    title: "Murang'a Avocado Packing Station",
    slug: "muranga-avocado-packing-station",
    county: "Murang'a",
    town: "Murang'a",
    region: "Central",
    clientType: "Agricultural",
    serviceType: "Pump Installation",
    depth: 90,
    yield: "3.5 m³/hr",
    duration: "2 days",
    completionYear: 2024,
    description: "Pump upgrade and water treatment system for export avocado washing and packing station in Murang'a.",
    challenge: "Existing pump was undersized for GlobalGAP washing requirements. Water quality failed export chlorine standards.",
    solution: "Upgraded pump and installed chlorination dosing system with turbidity filter for export-grade water.",
    outcome: "Packing station now handles 8 tonnes of avocados daily. GlobalGAP certification maintained for EU market access.",
    featured: false,
    latitude: "-0.7235",
    longitude: "37.1547",
  },

  // More diverse projects
  {
    title: "Laikipia Wildlife Conservancy",
    slug: "laikipia-wildlife-conservancy-borehole",
    county: "Laikipia",
    town: "Nanyuki",
    region: "Central",
    clientType: "Conservation",
    serviceType: "Solar Pump Systems",
    depth: 130,
    yield: "6.0 m³/hr",
    duration: "6 days",
    completionYear: 2023,
    description: "Solar borehole system for wildlife conservancy in Laikipia, supplying water holes for elephants and other wildlife.",
    challenge: "Water holes in the 50,000-acre conservancy were drying up threatening elephant populations.",
    solution: "Drilled strategic borehole near ancient elephant migration route. Solar pump fills 3 natural water pans.",
    outcome: "Elephant herd of 120+ returned to area within 6 months. Conservancy tourism revenue up 45%.",
    featured: true,
    latitude: "0.0100",
    longitude: "36.9800",
  },
  {
    title: "Taita-Taveta Sisal Estate",
    slug: "taita-taveta-sisal-estate",
    county: "Taita-Taveta",
    town: "Voi",
    region: "Coast",
    clientType: "Agricultural",
    serviceType: "Borehole Drilling",
    depth: 175,
    yield: "3.8 m³/hr",
    duration: "8 days",
    completionYear: 2022,
    description: "Borehole for 3,000-acre sisal estate in Taita-Taveta, providing water for fibre processing and workforce.",
    challenge: "Estate sits in a rain shadow valley between Taita Hills and Tsavo West. Very limited surface water.",
    solution: "Vertical electrical sounding survey located a productive fault zone aquifer at 155m depth.",
    outcome: "Estate processes 200 tonnes of sisal fibre monthly. 800 workforce families have domestic water access.",
    featured: false,
    latitude: "-3.3970",
    longitude: "38.5580",
  },
  {
    title: "Nandi Hills Tea Research Station",
    slug: "nandi-hills-tea-research-station",
    county: "Nandi",
    town: "Nandi Hills",
    region: "Rift Valley",
    clientType: "Research",
    serviceType: "Borehole Drilling",
    depth: 95,
    yield: "4.0 m³/hr",
    duration: "4 days",
    completionYear: 2024,
    description: "Research station borehole supporting KEFRI tea irrigation experiments and laboratory water needs.",
    challenge: "Research-grade water quality required. Existing surface supply was turbid during rains affecting experiment integrity.",
    solution: "Drilled into clean volcanic aquifer below weathered zone. Installed multi-barrier treatment for laboratory purity.",
    outcome: "Research station runs experiments year-round without weather interruption. Water quality meets ISO laboratory standards.",
    featured: false,
    latitude: "0.1980",
    longitude: "35.1450",
  },
  {
    title: "Vihiga County Health Facilities Water",
    slug: "vihiga-county-health-facilities",
    county: "Vihiga",
    town: "Mbale",
    region: "Western",
    clientType: "Healthcare",
    serviceType: "Borehole Drilling",
    depth: 100,
    yield: "3.0 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Network borehole serving 6 health facilities in Vihiga County under a county government WASH programme.",
    challenge: "6 facilities spread across hilly terrain at different elevations. Single source needed to serve all via gravity.",
    solution: "Sited borehole at highest elevation, installed high-head pump to elevated tank feeding all 6 facilities by gravity.",
    outcome: "All 6 health facilities have reliable water. Infection control metrics improved across the network.",
    featured: false,
    latitude: "0.0833",
    longitude: "34.7167",
  },
  {
    title: "Trans Nzoia Wheat Farm Irrigation",
    slug: "trans-nzoia-wheat-farm-irrigation",
    county: "Trans Nzoia",
    town: "Kitale",
    region: "Rift Valley",
    clientType: "Agricultural",
    serviceType: "Solar Pump Systems",
    depth: 80,
    yield: "7.5 m³/hr",
    duration: "4 days",
    completionYear: 2024,
    description: "Solar-powered borehole irrigation for 500-acre wheat farm in Trans Nzoia, Kenya's breadbasket county.",
    challenge: "Wheat farm in Kenya's breadbasket suffering from unpredictable short rains causing crop failures.",
    solution: "Drilled high-yield borehole in the Kitale alluvial deposits. 6kW solar pump feeds centre-pivot irrigation system.",
    outcome: "Farm produced record 1,800 tonnes of wheat in 2024 despite below-average rainfall. Employment doubled to 80 workers.",
    featured: false,
    latitude: "1.0153",
    longitude: "35.0064",
  },
  {
    title: "Homa Bay Fish Processing Plant",
    slug: "homa-bay-fish-processing-plant",
    county: "Homa Bay",
    town: "Homa Bay",
    region: "Nyanza",
    clientType: "Commercial",
    serviceType: "Borehole Drilling",
    depth: 110,
    yield: "5.0 m³/hr",
    duration: "5 days",
    completionYear: 2023,
    description: "Borehole for lakeside fish processing and export facility, replacing contaminated lake water intake.",
    challenge: "Lake Victoria water quality failing KEBS standards for food processing due to algal blooms.",
    solution: "Drilled away from lake shore tapping clean lacustrine aquifer. RO polishing unit installed for process water.",
    outcome: "Processing plant achieved KEBS food-grade certification. Now exports 30 tonnes of tilapia weekly to UAE.",
    featured: false,
    latitude: "-0.5267",
    longitude: "34.4571",
  },
  {
    title: "Samburu National Reserve Camp",
    slug: "samburu-national-reserve-camp",
    county: "Samburu",
    town: "Archer's Post",
    region: "North Eastern",
    clientType: "Hospitality",
    serviceType: "Solar Pump Systems",
    depth: 85,
    yield: "2.8 m³/hr",
    duration: "4 days",
    completionYear: 2022,
    description: "Off-grid solar borehole for luxury tented camp in Samburu National Reserve, replacing daily water deliveries.",
    challenge: "Remote national reserve location. Water deliveries cost KES 80,000/week. Zero grid power available.",
    solution: "Drilled shallow borehole in Ewaso Ngiro river flood plain. 3kW solar pump with battery backup for cloudy days.",
    outcome: "Camp is water-independent. Safari guests enjoy reliable hot water and pool. KES 4M annual savings.",
    featured: false,
    latitude: "0.6620",
    longitude: "37.5530",
  },
  {
    title: "Nyamira Tea Factory Water Supply",
    slug: "nyamira-tea-factory-water-supply",
    county: "Nyamira",
    town: "Nyamira",
    region: "Nyanza",
    clientType: "Commercial",
    serviceType: "Borehole Drilling",
    depth: 95,
    yield: "6.5 m³/hr",
    duration: "5 days",
    completionYear: 2024,
    description: "Borehole for KTDA tea factory in Nyamira, providing process water for tea withering and fermentation.",
    challenge: "Tea factory processing 350 tonnes of green leaf/day needed consistent water for withering machines.",
    solution: "Drilled into the productive volcanic aquifer of the Nyamira Highlands at 85m depth.",
    outcome: "Factory runs at full capacity year-round. Tea quality consistent across all batches. KTDA inspection score 98/100.",
    featured: false,
    latitude: "-0.5667",
    longitude: "34.9333",
  },
  {
    title: "Marsabit Camel Market Water Point",
    slug: "marsabit-camel-market-water-point",
    county: "Marsabit",
    town: "Marsabit",
    region: "North Eastern",
    clientType: "Community",
    serviceType: "Borehole Drilling",
    depth: 105,
    yield: "2.5 m³/hr",
    duration: "6 days",
    completionYear: 2023,
    description: "Community borehole at Marsabit camel and livestock market serving traders from across northern Kenya.",
    challenge: "Northern Kenya's largest camel market had no permanent water source. Traders hauled water 40km for animals.",
    solution: "Drilled through volcanic rock on Mount Marsabit, tapping springs from the forest catchment at 95m depth.",
    outcome: "Market water costs reduced by 90%. Trading volumes increased 35% as traders from further afield attend.",
    featured: false,
    latitude: "2.3333",
    longitude: "37.9833",
  },
];

async function seedProjects() {
  console.log(`Seeding ${projects.length} projects...`);

  const existing = await db.select({ id: projectsTable.id }).from(projectsTable);
  if (existing.length > 0) {
    console.log(`Projects table already has ${existing.length} records — skipping.`);
    process.exit(0);
  }

  await db.insert(projectsTable).values(projects);
  console.log(`Seeded ${projects.length} projects successfully.`);
  process.exit(0);
}

seedProjects().catch((e) => {
  console.error(e);
  process.exit(1);
});
