import { db, productsTable } from "@workspace/db";

const products = [
  {
    name: "Grundfos SP 5A Submersible Pump",
    slug: "grundfos-sp-5a-submersible-pump",
    category: "Submersible Pumps",
    brand: "Grundfos",
    description: "High-efficiency submersible borehole pump suitable for depths up to 200m. Ideal for domestic and light commercial use.",
    price: "185000.00",
    comparePrice: "210000.00",
    inStock: true,
    stockQty: 12,
    specifications: { "Flow Rate": "5 m³/hr", "Max Depth": "200m", "Power": "1.5kW", "Outlet": "1.25 inch" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: true,
  },
  {
    name: "Grundfos SP 11A Submersible Pump",
    slug: "grundfos-sp-11a-submersible-pump",
    category: "Submersible Pumps",
    brand: "Grundfos",
    description: "Heavy-duty submersible pump for commercial and agricultural boreholes with high yield requirements.",
    price: "320000.00",
    comparePrice: "360000.00",
    inStock: true,
    stockQty: 8,
    specifications: { "Flow Rate": "11 m³/hr", "Max Depth": "250m", "Power": "4kW", "Outlet": "2 inch" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: true,
  },
  {
    name: "Solar Pump Controller 3kW",
    slug: "solar-pump-controller-3kw",
    category: "Solar Pump Systems",
    brand: "Lorentz",
    description: "MPPT solar pump controller for off-grid borehole pumping. Compatible with most AC and DC submersible pumps.",
    price: "95000.00",
    comparePrice: null,
    inStock: true,
    stockQty: 15,
    specifications: { "Power": "3kW", "Input Voltage": "48-400V DC", "Output": "3-phase AC", "Protection": "IP65" },
    deliveryAvailable: true,
    deliveryDays: 5,
    whatsappOrderEnabled: true,
    featured: true,
  },
  {
    name: "Lorentz PS2 Solar Pump System",
    slug: "lorentz-ps2-solar-pump-system",
    category: "Solar Pump Systems",
    brand: "Lorentz",
    description: "Complete off-grid solar pump system including pump, controller and mounting hardware. Ideal for remote farms.",
    price: "450000.00",
    comparePrice: "500000.00",
    inStock: true,
    stockQty: 5,
    specifications: { "Flow Rate": "8 m³/hr", "Solar Input": "5kW", "Max Head": "120m", "Warranty": "5 years" },
    deliveryAvailable: true,
    deliveryDays: 7,
    whatsappOrderEnabled: true,
    featured: true,
  },
  {
    name: "uPVC Borehole Casing Pipe 6 inch",
    slug: "upvc-borehole-casing-6inch",
    category: "Borehole Casing",
    brand: null,
    description: "High-strength uPVC borehole casing pipe, 6 inch diameter, sold per metre. Suitable for boreholes up to 150m.",
    price: "3500.00",
    comparePrice: null,
    inStock: true,
    stockQty: 500,
    specifications: { "Diameter": "6 inch", "Material": "uPVC", "Length": "per metre", "Pressure Rating": "PN10" },
    deliveryAvailable: true,
    deliveryDays: 2,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "Stainless Steel Borehole Screen 6 inch",
    slug: "stainless-steel-borehole-screen-6inch",
    category: "Borehole Casing",
    brand: null,
    description: "304 stainless steel slotted screen for borehole water intake. Prevents sand ingress while maximising yield.",
    price: "8500.00",
    comparePrice: null,
    inStock: true,
    stockQty: 200,
    specifications: { "Diameter": "6 inch", "Material": "304 SS", "Slot Size": "0.5mm", "Length": "per metre" },
    deliveryAvailable: true,
    deliveryDays: 2,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "UV Water Steriliser 1000 LPH",
    slug: "uv-water-steriliser-1000lph",
    category: "Water Treatment",
    brand: "Watts",
    description: "Ultraviolet water sterilisation unit eliminating bacteria and viruses. Suitable for domestic and light commercial use.",
    price: "45000.00",
    comparePrice: "52000.00",
    inStock: true,
    stockQty: 20,
    specifications: { "Flow Rate": "1000 LPH", "UV Dose": "30 mJ/cm²", "Power": "55W", "Connection": "1 inch BSP" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "Reverse Osmosis System 500 LPH",
    slug: "reverse-osmosis-500lph",
    category: "Water Treatment",
    brand: "Pentair",
    description: "Commercial reverse osmosis system for borehole water desalination and purification. Removes up to 99% of dissolved solids.",
    price: "380000.00",
    comparePrice: "420000.00",
    inStock: true,
    stockQty: 4,
    specifications: { "Capacity": "500 LPH", "Rejection Rate": "99%", "Recovery": "75%", "Power": "1.5kW" },
    deliveryAvailable: true,
    deliveryDays: 7,
    whatsappOrderEnabled: true,
    featured: true,
  },
  {
    name: "Water Level Meter 100m",
    slug: "water-level-meter-100m",
    category: "Borehole Equipment",
    brand: "Solinst",
    description: "Electronic water level meter for borehole depth measurement. 100m cable with LED and buzzer indicator.",
    price: "28000.00",
    comparePrice: null,
    inStock: true,
    stockQty: 10,
    specifications: { "Cable Length": "100m", "Accuracy": "±1mm", "Probe Diameter": "9.5mm", "Display": "LED + Buzzer" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "HDPE Rising Main Pipe 32mm",
    slug: "hdpe-rising-main-32mm",
    category: "Borehole Equipment",
    brand: null,
    description: "High-density polyethylene rising main for submersible pump installation. Lightweight and corrosion-resistant.",
    price: "850.00",
    comparePrice: null,
    inStock: true,
    stockQty: 1000,
    specifications: { "Diameter": "32mm", "Material": "HDPE", "Pressure Rating": "PN16", "Length": "per metre" },
    deliveryAvailable: true,
    deliveryDays: 2,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "Pressure Tank 100L",
    slug: "pressure-tank-100l",
    category: "Pump Accessories",
    brand: "Reflex",
    description: "Diaphragm pressure tank for constant pressure water systems. Reduces pump cycling and extends pump life.",
    price: "32000.00",
    comparePrice: "38000.00",
    inStock: true,
    stockQty: 18,
    specifications: { "Capacity": "100L", "Max Pressure": "10 bar", "Connection": "1 inch BSP", "Material": "Carbon Steel" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: false,
  },
  {
    name: "Borehole Flow Meter 2 inch",
    slug: "borehole-flow-meter-2inch",
    category: "Borehole Equipment",
    brand: "Sensus",
    description: "Mechanical water flow meter for borehole yield monitoring and billing. Suitable for 2 inch pipework.",
    price: "18500.00",
    comparePrice: null,
    inStock: true,
    stockQty: 25,
    specifications: { "Size": "2 inch", "Max Flow": "15 m³/hr", "Accuracy": "±2%", "Material": "Brass" },
    deliveryAvailable: true,
    deliveryDays: 3,
    whatsappOrderEnabled: true,
    featured: false,
  },
];

async function seedProducts() {
  console.log(`Seeding ${products.length} products...`);

  const existing = await db.select({ id: productsTable.id }).from(productsTable);
  if (existing.length > 0) {
    console.log(`Products table already has ${existing.length} records — skipping.`);
    process.exit(0);
  }

  await db.insert(productsTable).values(products);
  console.log(`Seeded ${products.length} products successfully.`);
  process.exit(0);
}

seedProducts().catch((e) => {
  console.error(e);
  process.exit(1);
});
